name: Compile OpenSSL For Android New

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  OPENSSL_VERSION: 3.5.0
  WORK_PATH: /home/runner/work/openssl_for_android/openssl_for_android

jobs:
  Compile_OpenSSL_for_Android:
    name: Compile OpenSSL
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        info:
          - '{ "ANDROID_TARGET_ABI": "armeabi-v7a", "ANDROID_TARGET_API": "21",  "ANDROID_NDK": "r27c"}'
          - '{ "ANDROID_TARGET_ABI": "arm64-v8a",   "ANDROID_TARGET_API": "21",  "ANDROID_NDK": "r27c"}'
          - '{ "ANDROID_TARGET_ABI": "riscv64",     "ANDROID_TARGET_API": "35",  "ANDROID_NDK": "r27c"}'
          - '{ "ANDROID_TARGET_ABI": "x86",         "ANDROID_TARGET_API": "21",  "ANDROID_NDK": "r27c"}'
          - '{ "ANDROID_TARGET_ABI": "x86_64",      "ANDROID_TARGET_API": "21",  "ANDROID_NDK": "r27c"}'
    
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Aria2
        run: |
          sudo apt -yqq update
          sudo apt install -yqq aria2
      
      - name: Download Android NDK
        id: download_ndk
        run: |
          aria2c https://dl.google.com/android/repository/android-ndk-${{fromJSON(matrix.info).ANDROID_NDK}}-linux.zip
          unzip android-ndk-${{fromJSON(matrix.info).ANDROID_NDK}}-linux-x86_64.zip
          echo "::set-output name=status::success"

      - name: Download OpenSSL
        id: download_openssl
        run: |
          aria2c https://github.com/openssl/openssl/releases/download/openssl-${{env.OPENSSL_VERSION}}/openssl-${{env.OPENSSL_VERSION}}.tar.gz
          tar -zxvf openssl-${{env.OPENSSL_VERSION}}.tar.gz
          echo "::set-output name=status::success"

      - name: Compile
        id: compile
        if: steps.download_ndk.outputs.status == 'success' && steps.download_openssl.outputs.status == 'success' && !cancelled()
        run: |
          bash ./openssl_build_new.sh ${{fromJSON(matrix.info).ANDROID_TARGET_API}} ${{fromJSON(matrix.info).ANDROID_TARGET_ABI}} ${{env.OPENSSL_VERSION}} ${{fromJSON(matrix.info).ANDROID_NDK}}
          echo "::set-output name=status::success"

      - name: Generate release tag
        id: tag
        run: |
          tar -zcvf OpenSSL_${{env.OPENSSL_VERSION}}_${{fromJSON(matrix.info).ANDROID_TARGET_ABI}}.tar.gz openssl_${{env.OPENSSL_VERSION}}_${{fromJSON(matrix.info).ANDROID_TARGET_ABI}}
          echo "::set-output name=release_tag::${{env.OPENSSL_VERSION}}"
          echo "::set-output name=status::success"
      
      - name: Upload firmware to release
        if: steps.tag.outputs.status == 'success' && !cancelled()
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{steps.tag.outputs.release_tag}}
          files: ${{env.WORK_PATH}}/OpenSSL_${{env.OPENSSL_VERSION}}_${{fromJSON(matrix.info).ANDROID_TARGET_ABI}}.tar.gz


  Delete_Workflow:
    needs: [ Compile_OpenSSL_for_Android ]
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 8
