name: Compile OpenSSL For Android New

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  OPENSSL_VERSION: 3.6.1
  WORK_PATH: /home/runner/work/openssl_for_android/openssl_for_android

jobs:
  Compile_OpenSSL_for_Android:
    name: Compile OpenSSL
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        info:
          - '{ "ANDROID_TARGET_ABI": "armeabi-v7a", "ANDROID_TARGET_API": "21",  "ANDROID_NDK": "r27d"}'
          - '{ "ANDROID_TARGET_ABI": "arm64-v8a",   "ANDROID_TARGET_API": "21",  "ANDROID_NDK": "r27d"}'
          - '{ "ANDROID_TARGET_ABI": "riscv64",     "ANDROID_TARGET_API": "35",  "ANDROID_NDK": "r27d"}'
          - '{ "ANDROID_TARGET_ABI": "x86",         "ANDROID_TARGET_API": "21",  "ANDROID_NDK": "r27d"}'
          - '{ "ANDROID_TARGET_ABI": "x86_64",      "ANDROID_TARGET_API": "21",  "ANDROID_NDK": "r27d"}'
    
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Install Aria2
        run: |
          sudo apt -yqq update
          sudo apt install -yqq aria2
      
      - name: Download Android NDK
        run: |
          aria2c -o android-ndk-${{fromJSON(matrix.info).ANDROID_NDK}}.zip https://dl.google.com/android/repository/android-ndk-${{fromJSON(matrix.info).ANDROID_NDK}}-linux.zip
          unzip android-ndk-${{fromJSON(matrix.info).ANDROID_NDK}}.zip

      - name: Download OpenSSL
        run: |
          aria2c -o openssl-${{env.OPENSSL_VERSION}}.tar.gz https://github.com/openssl/openssl/releases/download/openssl-${{env.OPENSSL_VERSION}}/openssl-${{env.OPENSSL_VERSION}}.tar.gz
          tar -zxvf openssl-${{env.OPENSSL_VERSION}}.tar.gz

      - name: Compile
        id: compile
        run: |
          bash ./openssl_build_new.sh ${{fromJSON(matrix.info).ANDROID_TARGET_API}} ${{fromJSON(matrix.info).ANDROID_TARGET_ABI}} ${{env.OPENSSL_VERSION}} ${{fromJSON(matrix.info).ANDROID_NDK}}
          tar -zcvf OpenSSL_${{env.OPENSSL_VERSION}}_${{fromJSON(matrix.info).ANDROID_TARGET_ABI}}.tar.gz openssl_${{env.OPENSSL_VERSION}}_${{fromJSON(matrix.info).ANDROID_TARGET_ABI}}
          echo "status=success" >> $GITHUB_OUTPUT
      
      - name: Upload firmware to release
        if: steps.compile.outputs.status == 'success' && !cancelled()
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{secrets.GITHUB_TOKEN}}
          file_glob: true
          file: ${{env.WORK_PATH}}/OpenSSL_${{env.OPENSSL_VERSION}}_${{fromJSON(matrix.info).ANDROID_TARGET_ABI}}.tar.gz
          tag: ${{env.OPENSSL_VERSION}}
          overwrite: true
          body: |
            |ABI|API|NDK|
            |:-|:-:|:-:|
            |armeabi|21|r16b|
            |armeabi-v7a|21|r27d|
            |arm64-v8a|21|r27d|
            |mips|21|r16b|
            |mips64|21|r16b|
            |riscv64|35|r27d|
            |x86|21|r27d|
            |x86_64|21|r27d|

  Delete_Workflow:
    needs: [ Compile_OpenSSL_for_Android ]
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 8
