# This is a basic workflow to help you get started with Actions

name: build OpenSSL for Android

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install aria2
        run: |
          sudo apt -yqq update
          sudo apt install -yqq aria2
      
      - name: Download Android NDK
        id: download_ndk
        run: |
          aria2c https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip?hl=zh_cn
          unzip android-ndk-r14b-linux-x86_64.zip
          echo "::set-output name=status::success"

      - name: Download OpenSSL
        id: download_openssl
        run: |
          aria2c https://codeload.github.com/openssl/openssl/zip/OpenSSL_1_1_1i
          unzip openssl-OpenSSL_1_1_1i.zip
          echo "::set-output name=status::success"

      # Runs a set of commands using the runners shell
      - name: Compile openssl for Android
        id: compile
        if: steps.download_ndk.outputs.status == 'success' && steps.download_openssl.outputs.status == 'success'
        run: |
          rm -rf build
          mkdir build
          bash ./openssl_build_armeabi.sh
          echo "::set-output name=status::success"

      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: lib
          path: build/*.zip
      
