# This is a basic workflow to help you get started with Actions

name: build OpenSSL for Android

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install aria2
        run: |
          sudo apt -yqq update
          sudo apt install -yqq aria2
      
      - name: Get Android NDK
        run: |
          aria2c https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip?hl=zh_cn
          unzip android-ndk-r14b-linux-x86_64.zip

      - name: Get OpenSSL
        run: |
          aria2c https://codeload.github.com/openssl/openssl/zip/OpenSSL_1_1_1i
          unzip openssl-OpenSSL_1_1_1i.zip

      # Runs a set of commands using the runners shell
      - name: build openssl
        run: bash ./openssl_build_all.sh
